---
abstract: 'DB connection manager with Scope::Container'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  DBD::SQLite: 0
  ExtUtils::MakeMaker: 6.36
  File::Temp: 0
  Test::More: 0
  Test::SharedFork: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Scope-Container-DBI
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DBI: 1.615
  Data::Dumper: 0
  List::Util: 0
  Log::Minimal: 0
  Module::Load: 0
  Scope::Container: 0.04
  Try::Tiny: 0.11
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kazeburo/Scope-Container-DBI.git
version: 0.08
